### PR TITLE
fix: expired tokens broke the metal cli #81

### LINKED ISSUE #81: Expired Tokens break the metal CLI
With an expired token, the whole metal CLI is broken and fails with:

```bash
$ metal login --provider github
Error: the token has expired at 2025-04-26 02:08:04 +0200 CEST. please re-login through the login command
```

The same error will event be thrown for setting up completions, help and the context subcommands.

This seems to be regression of #75

### PR DESCRIPTION
**Pull request by vknabel**
Fixes #81

### CODE REVIEW

File: cmd/root.go [hunk 1]
```diff
@@ -164,3 +145,35 @@ func recursiveAutoGenDisable(cmd *cobra.Command) {
...
+
+func printErrorWithHints(c *config.Config, cmd *cobra.Command, err error) {
+	var connectErr *connect.Error
+	if !errors.As(err, &connectErr) || connectErr.Code() != connect.CodeUnauthenticated {
+		cmd.PrintErrln(err)
+		return
+	}
+
+	token := c.GetToken()
+	if token != "" {
```
Comment (Gerrit91) [inline cmd/root.go:157]: Potential swallow of printing any error.

Comment (vknabel) [reply cmd/root.go:157]: Done!
